### ISSUE TITLE
len(self.lowResQualityFiles) > 0 is always truthy

### ISSUE THREAD

**Issue by dsoloviov** [radosuav/pyDMS#3]
Hello!

My friend asked me to help troubleshoot the program, she is having some AttributeError exceptions. I spent some time trying to figure it out. Looks like the problem is [here](https://github.com/radosuav/pyDMS/blob/master/run_pyDMS.py#L18)

As far as I understand, `lowResMaskFilename` is supposed to be optional. If it's specified, some additional magic (sorry, have no idea what the script actually does :) ) happens, and you control it [here](https://github.com/radosuav/pyDMS/blob/master/pyDMS.py#L319). The problem is, `self.useQuality_LR` is always `True`, because when you check

```python
if len(self.lowResQualityFiles) > 0:
            self.useQuality_LR = True
```

you get single empty string as element of `self.lowResQualityFiles` list. So the length of list is always > 0, because empty string is a legit array element. So when the condition above resolves to `True`, program tries to open the file which is not there. Hence the AttributeError.

For now I asked my friend to either specify `lowResMaskFilename` or change the condition to

```python
if len(self.lowResQualityFiles) > 1:
            self.useQuality_LR = True
```

just to unblock here. But latter is a dirty hack, I understand that :)

Could you please look into this?

**Comment by radosuav** [comment]
Hi,
I always set lowResQualityFiles to an empty list if I don't want them to be used:
```
"lowResFiles":                [lowResFilename],
"lowResQualityFiles":         [], 
"lowResGoodQualityFlags":     [255],
```
But I agree that this is confusing so later today I'll change it so empty string will also set useQuality_LR to False.

**Comment by dsoloviov** [comment]
Great, thanks for such a quick response. Feel free to close this issue then.
